name: 'Validate a GitGitGadget configuration'
description: 'Parses and validates a JSON-formatted string containing a GitGitGadget configuration'
author: 'Johannes Schindelin'
inputs:
  config:
    description: 'The GitGitGadget configuration to use (see https://github.com/gitgitgadget/gitgitgadget/blob/HEAD/lib/project-config.ts)'
    required: false # not just yet...
runs:
  using: 'node20'
  main: './index.js'
branding:
  icon: 'git-commit'
  color: 'orange'