name: Test the GitHub Action

on:
  push:

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: ./init
      with:
        gitgitgadget-git-access-token: ${{ steps.gitgitgadget-git-token.outputs.token }}
        git-git-access-token: ${{ steps.git-git-token.outputs.token }}
        dscho-git-access-token: ${{ steps.dscho-git-token.outputs.token }}
