name: Test
on:
  push:

env:
  GITGITGADGET_DRY_RUN: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fail: ['true', 'false']
    steps:
      - name: Obtain config
        run: |
          set -x
          CONFIG="$(curl -L https://github.com/cygwingitgadget/gitgitgadget-workflows/raw/config/gitgitgadget-config.json)" &&
          printf 'CONFIG<<EOF\n%s\nEOF\n' "$CONFIG" >>$GITHUB_ENV
          cat $GITHUB_ENV
      - uses: actions/checkout@v5
      - uses: ./check-run
        with:
          config: ${{ env.CONFIG }}
          pr-url: https://github.com/cygwingitgadget/cygwin/pull/1
          name: name
          title: title
          summary: summary
      - name: Do${{ matrix.fail == 'false' && ' not' || '' }} fail
        run: set -x && exit ${{ matrix.fail == 'false' && '0' || '1' }}
