name: Test
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fail: ['true', 'false']
    steps:
      - uses: actions/checkout@v5
      - uses: ./check-run
      - name: Do${{ matrix.fail == 'false' && ' not' || '' }} fail
        run: set -x && exit ${{ matrix.fail == 'false' && '0' || '1' }}
